Adds documentation
fire2a/C2F-W pull request #84
Opened 2024-12-18 20:38 UTC by matildeRivas

2024-12-19 15:07 UTC, matildeRivas commented
@fdobad puedes ver si te funciona en tu compu porfa?

2024-12-19 20:04 UTC, fdobad commented
> @fdobad puedes ver si te funciona en tu compu porfa?
![image](https://github.com/user-attachments/assets/9308dc96-7d6c-449c-86a8-df29fa7a6232)

algo hay que hacerle a docs/html/index.html que se ve desierto.

apuntando acá C2F-W/docs/html/dc/d0a/classCell2Fire.html por último ?

2024-12-20 15:40 UTC, matildeRivas commented
> > @fdobad puedes ver si te funciona en tu compu porfa?
> > sí,
> > ![image](https://private-user-images.githubusercontent.com/29801096/397516480-6284e3c7-5ca9-4462-80f4-c19756800385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MDk0OTEsIm5iZiI6MTczNDcwOTE5MSwicGF0aCI6Ii8yOTgwMTA5Ni8zOTc1MTY0ODAtNjI4NGUzYzctNWNhOS00NDYyLTgwZjQtYzE5NzU2ODAwMzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDE1Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YzEyZGVmZTkwOTVkNDMxZjhlODcwMWViZDQ0Y2Q5NmI4MDcwMTM0NGQ0MzMyZGI4MzUxOTM2NzhmMTMyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GCcgshLzaeGNQz6x2wXVmVP203LB7haUT2JtKmY4Qyc)
> 
> algo hay que hacerle a docs/html/index.html que se ve desierto.
> 
> apuntando acá C2F-W/docs/html/dc/d0a/classCell2Fire.html por último ?

Sí, cuando esté buscando algo que hacer me meteré a jugar con Doxygen

2024-12-24 01:31 UTC, fdobad requested changes
no quitar ese argumento "C" es fuera de contexto

2024-12-24 01:31 UTC, fdobad commented on Cell2Fire/Cells.cpp
> -					 mainstruct.c * args->BFactor,
quitar el argumento "mainstruct.c" no es relevante al feature, volver atrás para no mezclar

2024-12-24 01:31 UTC, fdobad commented on Cell2Fire/Cells.cpp
> -void Cells::ros_distr_V2(double thetafire, double a, double b, double c, double EFactor)
quitar "double c" no es relevante para el feature, volver

2024-12-24 01:31 UTC, fdobad commented on Cell2Fire/Cells.cpp
> -					 mainstruct.c * EllipseFactors[2],
idem mainstruct.c * EllipseFactors[2],

2024-12-24 01:31 UTC, fdobad commented on Cell2Fire/Cells.h
> -	void ros_distr_V2(double thetafire, double a, double b, double c, double EFactor);
idem double c

2024-12-30 15:00 UTC, matildeRivas commented
Creo que está bien apra una primera versión, falta lo más importante que sería los command line arguments pero yo no sé cuáles son

2025-01-02 16:42 UTC, merged